name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/btn/fouiller.png
    - assets/btn/voir.png
    - assets/btn/ramasser.png
    - assets/btn/deposer.png
    - assets/img/robotpixel.webp
    - assets/img/robotpixel.jpg
  fonts:
    - family: 'SourceCodePro'
      fonts:
        - asset: assets/font/SourceCodePro.ttf